eluminate_web/apps/events/urls.py
from django.conf.urls import patterns, url
from .views import EventDetail, EventList, EventListUser
from .views import EventCreate, EventUpdate, EventDelete

urlpatterns = patterns('',
    url(r'^$', EventList.as_view(), name ='events-list'),
    url(r'^create$', EventCreate.as_view(), name="event-create"),
    url(r'^map$', EventList.as_view(template_name="events/event_map.html"), name="events-map"),
    url(r'^calendar$', EventList.as_view(template_name="events/event_calendar.html"), name="events-calendar"),
    url(r'^my-events$', EventListUser.as_view(), name="events-list-user"),
    url(r'^(?P<pk>\d+)/$', EventDetail.as_view(), name ='event-detail'),
    url(r'^(?P<pk>\d+)/update', EventUpdate.as_view(), name = "event-update"),
    url(r'^(?P<pk>\d+)/delete', EventDelete.as_view(), name="event-delete")
)

eluminate_web/apps/maps/urls.py
from django.conf import settings
from django.conf.urls import  patterns, url

urlpatterns = patterns('maps.views',
                       url(r'^$', 'list', name='locations_list'),
                       url(r'edit/(\d+)', 'edit', name='edit_location'),
                       url(r'add', 'add', name='add_location'),
                       url(r'delete/(\d+)', 'delete', name='delete_location'),
)

eluminate_web/apps/participant/urls.py
from django.conf.urls import patterns, url

from .views import ParticipantLandingView, ParticipantDetailView, ParticipantFilterRedirectView, \
                   ParticipantCreateView, ParticipantUpdateView, ParticipantDeleteView


urlpatterns = patterns('participant.views',
    url(r'^$', ParticipantLandingView.as_view(), name='participant_landing'),
    url(r'^create$', ParticipantCreateView.as_view(), name="participant_create"),
    url(r'^filter/$', ParticipantFilterRedirectView.as_view(), name='participant_filter'),
    url(r'^(?P<slug>[a-z0-9_\-]+)/$', ParticipantDetailView.as_view(), name='participant_detail'),
    url(r'^(?P<slug>[a-z0-9_\-]+)/update/$', ParticipantUpdateView.as_view(), name="participant_update"),
    url(r'^(?P<slug>[a-z0-9_\-]+)/delete/$', ParticipantDeleteView.as_view(), name="participant_delete")
)

eluminate_web/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns("",
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),

    url(r'^participants/', include("participant.urls")),
    url(r'^sponsors/$', TemplateView.as_view(template_name="sponsors.html"), name="sponsors"),

    url(r'^about/$', TemplateView.as_view(template_name="about_vision.html"), name="about"),
    url(r'^about/vision/$', TemplateView.as_view(template_name="about_vision.html"), name="vision"),
    #url(r'^about/history/$', TemplateView.as_view(template_name="about_history.html"), name="history"),
    url(r'^about/people/$', TemplateView.as_view(template_name="about_people.html"), name="people"),
    url(r'^about/partners/$', TemplateView.as_view(template_name="about_partners.html"), name="partners"),
    url(r'^about/press/$', TemplateView.as_view(template_name="about_press.html"), name="press"),
    url(r'^about/news/$', TemplateView.as_view(template_name="about_news.html"), name="news"),

    url(r'^contact/$', TemplateView.as_view(template_name="contact.html"), name="contact"),
    url(r'^account/', include("custom_account.urls")),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^events/", include("events.urls")),  
    url(r'^maps/', include("maps.urls")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eluminate_web/apps/maps/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import User


class Location(models.Model):
    """Class for the location which couple with the User.
    If you curious about the SRID read here: 
    https://secure.wikimedia.org/wikipedia/en/wiki/SRID
    Of you want to know why 4326 and not 42 read here: 
        https://secure.wikimedia.org/wikipedia/en/wiki/WGS84
    """

    user = models.ForeignKey(User, related_name='location_set') 
    name = models.CharField(max_length=150, help_text="The name is used on to reference the location and it's visible on the map")
    marker = models.PointField(srid=4326) # the marker
    area = models.PolygonField(srid=4326, blank=True, null=True) #an area
    objects = models.GeoManager()

    def __unicode__(self):
        return self.name 
    
    class Meta:
        unique_together = ("user", "name")
    
    # Acces to maker:         self.marker.x, self.marker.y 
    # acess to area coords:   self.area.coords

eluminate_web/apps/custom_account/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.utils.translation import ugettext_lazy as _

from account.views import SignupView, ConfirmEmailView

from custom_account.forms import CustomSignupForm
from participant.models import Participant

class CustomSignupView(SignupView):

    form_class = CustomSignupForm

    def after_signup(self, form):
        self.create_participant(form)
        super(CustomSignupView, self).after_signup(form)

    def create_participant(self, form):
        participant = Participant(
            user = self.created_user,
            name = form.cleaned_data.get("participant_name"),
            slug = form.cleaned_data.get("participant_slug"),
            website = form.cleaned_data.get("participant_website"),
            logo = form.cleaned_data.get("participant_logo"),
            photo = form.cleaned_data.get("participant_photo"),
            description = form.cleaned_data.get("participant_description")
        )
        participant.save()
        for category in form.cleaned_data.get("participant_categories"):
            participant.categories.add(category)
        participant.save()


class CustomConfirmEmailView(ConfirmEmailView):

    ConfirmEmailView.messages["email_confirmed"]["text"] = _("You have confirmed %(email)s for user account %(username)s")
    
    def post(self, *args, **kwargs):
        self.object = confirmation = self.get_object()
        confirmation.confirm()
        user = confirmation.email_address.user
        user.is_active = True
        user.save()
        redirect_url = self.get_redirect_url()
        if not redirect_url:
            ctx = self.get_context_data()
            return self.render_to_response(ctx)
        if self.messages.get("email_confirmed"):
            messages.add_message(
                self.request,
                self.messages["email_confirmed"]["level"],
                self.messages["email_confirmed"]["text"] % {
                    "email": confirmation.email_address.email,
                    "username": confirmation.email_address.user.username
                }
            )
        return redirect("%s?next=%s" % (reverse(redirect_url), reverse('events-list-user')))

eluminate_web/apps/events/views.py
from django.db.models import Q, Min
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpResponseForbidden
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils.timezone import now
from django.contrib.gis.geos import Polygon
from django.db.models.query import EmptyQuerySet

from braces.views import LoginRequiredMixin

from maps.models import Location
from maps.utils import get_search_polygon, calculate_bounds
from participant.mixins import CategoryFilterMixin
from participant.models import Participant

from .models import Event
from .forms import EventForm
   
   
class EventParticipantApprovedMixin(object):
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        try:
            request.user.participant # Checking if the user is participant at all.
            
            if not request.user.participant.approved():
                msg = "Your Event will only be visible once you have been approved as a participant."
                messages.add_message(request, messages.INFO, msg)
                
        except ObjectDoesNotExist:
            return HttpResponseRedirect(reverse_lazy('home'))

        return super(EventParticipantApprovedMixin, self).dispatch(request, *args, **kwargs)
        
        
class EventModelOwnerRestrictedMixin(object):
    model = Event
    
    def get_queryset(self):
        "Restricting to only the Events the user owns."
        
        queryset = super(EventModelOwnerRestrictedMixin, self).get_queryset().filter(
                                    participant=self.request.user.participant
                                    )
        return queryset

class EventFormRestrictedQueryset(object):
    
    def get_form(self, form_class):
        form = super(EventFormRestrictedQueryset, self).get_form(form_class)
        form.fields['location'].queryset = Location.objects.filter(user=self.request.user)
        form.fields['collaborators'].queryset = Participant.objects.exclude(user=self.request.user)
        return form

class EventDetail(DetailView):
    model = Event
    
    def render_to_response(self, context, **kwargs):
        object = self.get_object()
        if not object.participant.approved():
            # If the current user is the same that has create the event we show it
            if self.request.user == object.participant.user:    
                msg = "Your Event will only be visible once you have been approved as a participant."
                messages.add_message(self.request, messages.INFO, msg)
                context = self.get_context_data(**kwargs)
            else: # for all the other we redirect to the homepage.
                return HttpResponseRedirect(reverse_lazy('home'))
        return super(EventDetail, self).render_to_response(context, **kwargs)
    
    

class EventList(CategoryFilterMixin, ListView):
    
    model = Event
    queryset = Event.objects.filter(participant__approved_on__lt=now())\
        .annotate(first_day=Min('days')).order_by('-featured','-isEvent','-priority')# .order_by('first_day', 'start_time')

    def get_queryset(self):
        queryset = super(EventList, self).get_queryset()

        if self.selected_category_id:
            owner_in_category_query = Q(participant__categories=self.selected_category_id)
            approved_collaborators_query = ~Q(collaborators__approved_on=None)
            collaborators_in_category_query = Q(collaborators__categories=self.selected_category_id)
            queryset = queryset.filter(owner_in_category_query | approved_collaborators_query & collaborators_in_category_query).distinct()

        if self.request.GET.has_key("q"):
            queryset = queryset.filter(name__icontains=self.request.GET["q"])
        return queryset
    
    def get_template_names(self):
        template = super(EventList, self).get_template_names()
        if self.request.is_ajax():
            template = "events/_event_map_list.html"
        return template
    
    def get(self, request, *args, **kwargs):
        if request.is_ajax(): #map has been zoomed or dragged.
            poly, map_bounds = get_search_polygon(request)
            self.object_list = self.get_queryset().filter(location__marker__within=poly)
            context = self.get_context_data(object_list=self.object_list)
            context['map_bounds'] = map_bounds
            return self.render_to_response(context, **kwargs)
        
        else: # we load the page for the first time.
            self.object_list = self.get_queryset()
            context = self.get_context_data(object_list=self.object_list)
            locations = Location.objects.filter(event__in=self.object_list)
            map_bounds = calculate_bounds(locations)
            context['map_bounds'] = map_bounds
            return self.render_to_response(context, **kwargs)

class EventListUser(EventModelOwnerRestrictedMixin, ListView):

    model = Event
    template_name = "events/event_list_user.html"
    
    
                

class EventCreate(EventParticipantApprovedMixin, EventFormRestrictedQueryset, CreateView):
    
    model = Event
    form_class = EventForm

    def form_valid(self, form):
        
        form.instance.participant = self.request.user.participant
        form.save()
        return super(EventCreate, self).form_valid(form)
        

class EventUpdate(EventParticipantApprovedMixin, EventModelOwnerRestrictedMixin, 
                  EventFormRestrictedQueryset, UpdateView):
        
    model = Event
    form_class = EventForm
    template_name = "events/event_form_update.html"
    
    
class EventDelete(EventParticipantApprovedMixin, EventModelOwnerRestrictedMixin, DeleteView):
    
    model = Event
    

eluminate_web/apps/maps/views.py
from django.template import RequestContext, Context
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from django.contrib.gis.geos import Point
from django.contrib import messages
from utils import calculate_center, DEFAULT_CENTER_OBJ, calculate_bounds
from forms import AddLocationForm, EditLocationForm
from models import Location



import logging
# Get an instance of a logger
logger = logging.getLogger(__name__)

@login_required
def list(request, template='maps/locations.html'):
    
    data = {}
    locations_obj = request.user.location_set.all()
    
    data['locations'] = locations_obj
    data['username'] = request.user.username
    if locations_obj:
        data['map_bounds'] = calculate_bounds(locations_obj)
    
    return render_to_response(template,
                  data,
                  context_instance=RequestContext(request)
                  )

@csrf_protect
@login_required    
def add(request, form_class=AddLocationForm, template='maps/add_location.html'):
    center_obj = DEFAULT_CENTER_OBJ
    if request.method == 'POST': # If the form has been submitted...
        form = form_class(request.user, request.POST)
        if form.is_valid():
            
            location = form.save(commit=False)
            location.user = request.user
            location.save()
            msg = _("%(name)s has been saved.") %{'name': location.name}
            messages.add_message(request, messages.SUCCESS, msg)
            
            if request.session.has_key('next'):
                redirect_url = request.session.get('next')
                return HttpResponseRedirect(redirect_url)
            return HttpResponseRedirect(reverse('locations_list'))
        else:
            # We re-pass the default location if the form is not valid
            location = Location()
            location.marker = Point(DEFAULT_CENTER_OBJ['x'], DEFAULT_CENTER_OBJ['y'])
        
    else:
        # A dynamically loaded form
        location = Location()
        location.marker = Point(DEFAULT_CENTER_OBJ['x'], DEFAULT_CENTER_OBJ['y'])
        form = form_class(initial={'user' : request.user,
                                   'marker' : location.marker})
        if request.GET.has_key('next'):
            request.session['next'] = request.GET['next']
        
    return render_to_response(template,
                              { "form": form, 
                                "location": location,
                               },
                              context_instance=RequestContext(request))

@csrf_protect
@login_required    
def edit(request, location_pk, form_class=EditLocationForm, template='maps/add_location.html'):
    
    location = get_object_or_404(Location, pk=location_pk)
    
    if location.user != request.user:    
        return HttpResponseRedirect(reverse('home'))
        
    if request.method == 'POST': # If the form has been submitted...    
        form = form_class(request.user, request.POST, instance=location)
        
        if form.is_valid():

            location = form.save(commit=False)
            location.save()
            msg = _("%(name)s has been saved.") %{'name': location.name}
            messages.add_message(request, messages.SUCCESS, msg)
            
            return HttpResponseRedirect(reverse('locations_list'))
        
        
    else:
        # A dynamically loaded form
        form = form_class(instance=location)
    return render_to_response(template,
                              { "form": form,
                                "location": location,
                                },
                              context_instance=RequestContext(request))
        
@csrf_protect
@login_required
def delete(request, location_pk):
    location = Location.objects.get(pk=location_pk)
    location.delete()
    return HttpResponseRedirect(reverse('locations_list'))

eluminate_web/templates/maps/_geographical_name_search.html
{% if lookup_address_length == 1 %}
	{% for address in lookup_address %}
		{% with name=address.0 latitude=address.1.0 longitude=address.1.1 %}
			<a href="{% url "inventory-item-list" %}?searched_lat={{latitude}}&searched_long={{longitude}}">{{name}}</a>
        {% endwith %}
	{% endfor %}
	
{% elif lookup_address_length > 1 %}
<div class="address-results">
	<p class="lead">Did you mean any of these?</p>
	<ul class="unstyled">
		{% for address in lookup_address %}
			{% with name=address.0 latitude=address.1.0 longitude=address.1.1 %}
			<li><a href="{% url "inventory-item-list" %}?searched_location={{name}}&searched_lat={{latitude}}&searched_long={{longitude}}">{{name}}</a></li>
			{% endwith %}
		{% endfor %}
	</ul>
</div>

{% endif %}

eluminate_web/templates/maps/_geographical_name_search_landing.html
<form action='' class="form-search" id="id_address_query">
	
	<input id="id_address_query_input" type="text" class="span6 greenbox" name="address_query">
  <button type="submit" class="btn greenbox">Search</button>
</form>

{% include "maps/_geographical_name_search.html" %}

eluminate_web/templates/maps/_geographical_name_search_market.html
<form action='' class="form-search" id="id_address_query">
	
	<input id="id_address_query_input" type="text" class="span3" 
	name="address_query" placeholder="{{searched_location}}">
  <button type="submit" class="btn">Search</button>
</form>

{% include "maps/_geographical_name_search.html"%}

eluminate_web/templates/maps/_map.html
{% extends "maps/_map_base.html" %}

eluminate_web/templates/maps/_map_base.html
<!-- Leaflet Map -->
<link rel="stylesheet" href="{{ STATIC_URL }}dist/leaflet.css" />
<!--[if lte IE 8]>
    <link rel="stylesheet" href="{{ STATIC }}css/leaflet.ie.css" />
<![endif]-->
<script src="{{ STATIC_URL }}dist/leaflet.js"></script>

{% comment %}
{# disabling the cluster plugin for now. #}
<!-- cluster plugin -->
<link rel="stylesheet" href="{{ STATIC_URL }}dist/MarkerCluster.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}dist/MarkerCluster.Default.css" />
<!--[if lte IE 8]><link rel="stylesheet" href="{{ STATIC_URL }}dist/MarkerCluster.Default.ie.css" /><![endif]-->
<script src="{{ STATIC_URL }}dist/leaflet.markercluster.js"></script>
{% endcomment %}

<!-- our script -->
<script src="{{ STATIC_URL }}js/map-interaction.js"></script>     
<!-- /Leaflet Map -->


{% block map_body %}
<div id="map_canvas"></div>
{% endblock %}

{% block map_ready %}
<script type="text/javascript">
    $(document).ready(function(){  
        SSOUK.map_handler.init();
    });
</script>
{% endblock %}

eluminate_web/templates/maps/_map_edit.html
{% extends "maps/_map_base.html" %}

{% block map_body %}{% endblock %}
{% block map_ready %}
<script type="text/javascript">
  var MARKER = null;

  function marker_change_cb(e) {
    var l = e.latlng == undefined ? e.target.getLatLng() : e.latlng;
    MARKER.setLatLng(l);
    $("#id_marker").val("POINT (" + l.lng + " " + l.lat + ")");
  }

  $(document).ready(function(){
    SSOUK.map_handler.init();
    var map = SSOUK.map_handler.map;
    MARKER = L.marker([{{ location.marker.y }}, {{ location.marker.x }}],
                      {"draggable": true}).addTo(map);
    map.panTo([{{ location.marker.y }}, {{ location.marker.x }}]);
    map.on("click", marker_change_cb);
    MARKER.on("dragend", marker_change_cb);
  });
</script>
{% endblock %}

eluminate_web/templates/maps/add_location.html
{% extends "site_base.html" %}

{% load crispy_forms_tags %}
{% block extra_head %}
	{{ form.media }}
<style>
#map_canvas { height: 400px; }
</style>
<!-- Leaflet Map -->
<link rel="stylesheet" href="{{ STATIC_URL }}dist/leaflet.css" />
<!--[if lte IE 8]>
    <link rel="stylesheet" href="{{ STATIC }}css/leaflet.ie.css" />
<![endif]-->
<script src="{{ STATIC_URL }}dist/leaflet.js"></script>

{% comment %}
{# disabling the cluster plugin for now. #}
<!-- cluster plugin -->
<link rel="stylesheet" href="{{ STATIC_URL }}dist/MarkerCluster.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}dist/MarkerCluster.Default.css" />
<!--[if lte IE 8]><link rel="stylesheet" href="{{ STATIC_URL }}dist/MarkerCluster.Default.ie.css" /><![endif]-->
<script src="{{ STATIC_URL }}dist/leaflet.markercluster.js"></script>
{% endcomment %}

<!-- our script -->
<script src="{{ STATIC_URL }}js/map-interaction.js"></script>     
<!-- /Leaflet Map -->
{% endblock %}
{% block head_title %}Add New Location{% endblock %}

{% block body %}
{% include "maps/_map_edit.html" %}

<h1>New location</h1>

<div class="row">

	<div class="span8">
		<div class="row">
		    {% crispy form form.helper %}
		</div>
		
			
		
	</div>
</div>

{% endblock %}

eluminate_web/templates/maps/locations.html
{% extends "site_base.html" %}

{% block head_title %}{{ username }}'s Items{% endblock %}

{% block body %}

<h1>Manage Your locations</h1>

<div class="row">
	<div class="span12">
		<div class="row">
			<div class="span6">
				{% include "maps/_map.html" %}
				<style type="text/css">
				#map_canvas{
					height: 400px;
				}
				</style>
				{% if map_bounds %}
			      <script type="text/javascript">
			           $(document).ready(function(){ 
			            SSOUK.map_handler.map.fitBounds({{map_bounds}});
			          });
			      </script>
			  	{% endif %}
			</div>		
			<div class="span6">
				{% if locations %}
				<div id="location-user">    
				    {% for location in locations %}
				    	<div class="row">
				        	<div class="span2">
				        		<i id="marker_location_{{location.id}}" rel="tootltip" title="Click to locate on the map" class=icon-map-marker></i>
				        		 {{ location.name }}</div>
				        	<div class="span2"><a class="btn" 
				        		href="{% url edit_location location.pk %}">Edit the location</a></div>
				        	<div class="span2">
				        		<a class="btn btn-danger" 
				        			href=" {% url delete_location location.pk %}"
				        			title="There is no going back!">Delete Location</a>
				        	</div>
							<script type="text/javascript">
								$(document).ready(function(){	
					    		SSOUK.map_handler.updateMarker({{ location.marker.y }}, 
					    								   {{ location.marker.x }},
					    								   "{{ location.name }}", 
					    								   {{ location.id }});
							});
					    	</script>
	    					<script type="text/javascript">
								$(document).ready(function(){ 
                				$("#marker_location_{{location.id}}").on("click", {
                	                                            item_location_id: {{location.id}},
                	                                          },
                                SSOUK.map_handler.onInventoryListClick);
				             	});
                			</script>
					  	</div>
					  <hr/>
				    {% endfor %}
		    	</div>
				{% endif %}			
					<div class="row">
						<div class="offset2">
							<a class="btn btn-primary btn-large" href="{% url add_location %}">Add a new Location</a>	
						</div>    
				   	</div>			
				</div>
			</div>
		</div>
</div>


{% endblock %}

{% block extra_body %}
{% endblock %}