eluminate_web/apps/events/urls.py
from django.conf.urls import patterns, url
from .views import EventDetail, EventList, EventListUser
from .views import EventCreate, EventUpdate, EventDelete

urlpatterns = patterns('',
    url(r'^$', EventList.as_view(), name ='events-list'),
    url(r'^create$', EventCreate.as_view(), name="event-create"),
    url(r'^map$', EventList.as_view(template_name="events/event_map.html"), name="events-map"),
    url(r'^calendar$', EventList.as_view(template_name="events/event_calendar.html"), name="events-calendar"),
    url(r'^my-events$', EventListUser.as_view(), name="events-list-user"),
    url(r'^(?P<pk>\d+)/$', EventDetail.as_view(), name ='event-detail'),
    url(r'^(?P<pk>\d+)/update', EventUpdate.as_view(), name = "event-update"),
    url(r'^(?P<pk>\d+)/delete', EventDelete.as_view(), name="event-delete")
)

eluminate_web/apps/maps/urls.py
from django.conf import settings
from django.conf.urls import  patterns, url

urlpatterns = patterns('maps.views',
                       url(r'^$', 'list', name='locations_list'),
                       url(r'edit/(\d+)', 'edit', name='edit_location'),
                       url(r'add', 'add', name='add_location'),
                       url(r'delete/(\d+)', 'delete', name='delete_location'),
)

eluminate_web/apps/participant/urls.py
from django.conf.urls import patterns, url

from .views import ParticipantLandingView, ParticipantDetailView, ParticipantFilterRedirectView, \
                   ParticipantCreateView, ParticipantUpdateView, ParticipantDeleteView


urlpatterns = patterns('participant.views',
    url(r'^$', ParticipantLandingView.as_view(), name='participant_landing'),
    url(r'^create$', ParticipantCreateView.as_view(), name="participant_create"),
    url(r'^filter/$', ParticipantFilterRedirectView.as_view(), name='participant_filter'),
    url(r'^(?P<slug>[a-z0-9_\-]+)/$', ParticipantDetailView.as_view(), name='participant_detail'),
    url(r'^(?P<slug>[a-z0-9_\-]+)/update/$', ParticipantUpdateView.as_view(), name="participant_update"),
    url(r'^(?P<slug>[a-z0-9_\-]+)/delete/$', ParticipantDeleteView.as_view(), name="participant_delete")
)

eluminate_web/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns("",
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),

    url(r'^participants/', include("participant.urls")),
    url(r'^sponsors/$', TemplateView.as_view(template_name="sponsors.html"), name="sponsors"),

    url(r'^about/$', TemplateView.as_view(template_name="about_vision.html"), name="about"),
    url(r'^about/vision/$', TemplateView.as_view(template_name="about_vision.html"), name="vision"),
    #url(r'^about/history/$', TemplateView.as_view(template_name="about_history.html"), name="history"),
    url(r'^about/people/$', TemplateView.as_view(template_name="about_people.html"), name="people"),
    url(r'^about/partners/$', TemplateView.as_view(template_name="about_partners.html"), name="partners"),
    url(r'^about/press/$', TemplateView.as_view(template_name="about_press.html"), name="press"),
    url(r'^about/news/$', TemplateView.as_view(template_name="about_news.html"), name="news"),

    url(r'^contact/$', TemplateView.as_view(template_name="contact.html"), name="contact"),
    url(r'^account/', include("custom_account.urls")),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^events/", include("events.urls")),  
    url(r'^maps/', include("maps.urls")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eluminate_web/apps/events/models.py
from django.contrib.gis.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from django import forms

from south.modelsinspector import add_introspection_rules

from participant.models import Participant
from maps.models import Location

class Day(models.Model):
    name = models.CharField(max_length = 200)
    
    def __str__(self):
        
        return self.name

class EventSearchManager(models.Manager):
    def searched(self, term):
        return Event.objects.filter(name__icontains=term)

class Event(models.Model):
    name = models.CharField(max_length = 256, help_text="The name of the event")
    start_time = models.TimeField(help_text="When it starts, e.g. 12:00")
    end_time = models.TimeField(help_text="When the event finish, e.g. 16:00")
    days = models.ManyToManyField(Day)
    priority = models.IntegerField(default=0, help_text="Higher priority events appear nearer top")
    isEvent = models.BooleanField(default = True, help_text="check for events, uncheck for installations")
    featured = models.BooleanField(default= False, help_text="check to move item to top of list")
    participant = models.ForeignKey(Participant, related_name="own_events")
    collaborators = models.ManyToManyField(Participant, related_name="collaboration_events", 
                                           blank=True, null=True)
    photo = models.ImageField(upload_to='event_photos/%Y/%m/%d', max_length=200, blank=True, help_text=u'Event photo', default='')
    description = models.TextField()
    location = models.ForeignKey(Location, null=True)
    searched_objects = EventSearchManager()
    objects = models.GeoManager()

    def save(self, *args, **kwargs):
        if self.id and self.participant in self.collaborators.all():
            raise forms.ValidationError("Participant '%s' is a collaborator - can't be the owner too" % self.participant)
        else:
            super(Event, self).save()
    
    def get_absolute_url(self):
        return(reverse("event-detail", args=[self.id]))
    
    def __str__(self):
        return self.name

    def approved_collaborators(self):
        return self.collaborators.exclude(approved_on=None)

@receiver(m2m_changed, sender=Event.collaborators.through)
def collaborators_changed(sender, instance, action, pk_set, **kwargs):
    if action == "pre_add":
        if instance.participant.id in pk_set:
            raise forms.ValidationError("Participant '%s' is the owner - can't be a collaborator too" % instance.participant)

eluminate_web/apps/participant/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(unique=True, max_length=20)   

    class Meta:
        verbose_name_plural = u'Categories'

    def __unicode__(self):
        return self.name

class ParticipantsApprovedManager(models.Manager):
    def get_query_set(self):
        return super(ParticipantsApprovedManager, self).get_query_set().exclude(approved_on=None)

class Participant(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=255, help_text=u'Name of participating company')
    slug = models.SlugField(max_length=255, unique=True, help_text=u'Unique URL-safe version of name')
    website = models.CharField(max_length=2000, help_text=u'Website URL')
    logo = models.ImageField(upload_to='participant_logos/%Y/%m/%d', max_length=200, help_text=u'Company logo')
    photo = models.ImageField(upload_to='participant_photos/%Y/%m/%d', max_length=200, blank=True, help_text=u'Company photo')
    description = models.TextField(blank=True, help_text=u'Description of the participating company')
    categories = models.ManyToManyField(Category)
    created = models.DateTimeField(auto_now_add=True, help_text=u'Date/Time when company was first created')
    approved_on = models.DateTimeField(null=True, blank=True, help_text=u'Date/Time when company was approved to appear online')

    objects = models.Manager()
    objects_approved = ParticipantsApprovedManager()

    def __unicode__(self):
        return self.name

    def approved(self):
        return self.approved_on != None

    def approved_collaboration_events(self):
        return self.collaboration_events.exclude(participant__approved_on=None)

    def get_absolute_url(self):
        return reverse('participant_detail', kwargs={'slug': self.slug})

eluminate_web/apps/custom_account/forms.py
from django.forms import CharField, SlugField, ImageField, ModelMultipleChoiceField, \
                            Textarea

from account.forms import SignupForm
from participant.models import Category

class CustomSignupForm(SignupForm):
    participant_name = CharField(
    )
    participant_slug = SlugField(
        label = "Slug",
        help_text = "URL-safe version of above"
    )
    participant_website = CharField(
        label = "Website address (optional)",
        required = False, 
        initial = "http://"
    )
    participant_logo = ImageField(
        label = "Upload logo"
    )
    participant_photo = ImageField(
        label = "Upload a photo (optional)",
        required = False
    )
    participant_description = CharField(
        label = "Description",
        required = False, 
        widget = Textarea)
    participant_categories = ModelMultipleChoiceField(
        label = "Categories",
        help_text = "Select as many as apply using Ctrl key and mouse select",
        queryset = Category.objects.all()
    ) 

eluminate_web/apps/custom_account/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.utils.translation import ugettext_lazy as _

from account.views import SignupView, ConfirmEmailView

from custom_account.forms import CustomSignupForm
from participant.models import Participant

class CustomSignupView(SignupView):

    form_class = CustomSignupForm

    def after_signup(self, form):
        self.create_participant(form)
        super(CustomSignupView, self).after_signup(form)

    def create_participant(self, form):
        participant = Participant(
            user = self.created_user,
            name = form.cleaned_data.get("participant_name"),
            slug = form.cleaned_data.get("participant_slug"),
            website = form.cleaned_data.get("participant_website"),
            logo = form.cleaned_data.get("participant_logo"),
            photo = form.cleaned_data.get("participant_photo"),
            description = form.cleaned_data.get("participant_description")
        )
        participant.save()
        for category in form.cleaned_data.get("participant_categories"):
            participant.categories.add(category)
        participant.save()


class CustomConfirmEmailView(ConfirmEmailView):

    ConfirmEmailView.messages["email_confirmed"]["text"] = _("You have confirmed %(email)s for user account %(username)s")
    
    def post(self, *args, **kwargs):
        self.object = confirmation = self.get_object()
        confirmation.confirm()
        user = confirmation.email_address.user
        user.is_active = True
        user.save()
        redirect_url = self.get_redirect_url()
        if not redirect_url:
            ctx = self.get_context_data()
            return self.render_to_response(ctx)
        if self.messages.get("email_confirmed"):
            messages.add_message(
                self.request,
                self.messages["email_confirmed"]["level"],
                self.messages["email_confirmed"]["text"] % {
                    "email": confirmation.email_address.email,
                    "username": confirmation.email_address.user.username
                }
            )
        return redirect("%s?next=%s" % (reverse(redirect_url), reverse('events-list-user')))

eluminate_web/apps/events/views.py
from django.db.models import Q, Min
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpResponseForbidden
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils.timezone import now
from django.contrib.gis.geos import Polygon
from django.db.models.query import EmptyQuerySet

from braces.views import LoginRequiredMixin

from maps.models import Location
from maps.utils import get_search_polygon, calculate_bounds
from participant.mixins import CategoryFilterMixin
from participant.models import Participant

from .models import Event
from .forms import EventForm
   
   
class EventParticipantApprovedMixin(object):
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        try:
            request.user.participant # Checking if the user is participant at all.
            
            if not request.user.participant.approved():
                msg = "Your Event will only be visible once you have been approved as a participant."
                messages.add_message(request, messages.INFO, msg)
                
        except ObjectDoesNotExist:
            return HttpResponseRedirect(reverse_lazy('home'))

        return super(EventParticipantApprovedMixin, self).dispatch(request, *args, **kwargs)
        
        
class EventModelOwnerRestrictedMixin(object):
    model = Event
    
    def get_queryset(self):
        "Restricting to only the Events the user owns."
        
        queryset = super(EventModelOwnerRestrictedMixin, self).get_queryset().filter(
                                    participant=self.request.user.participant
                                    )
        return queryset

class EventFormRestrictedQueryset(object):
    
    def get_form(self, form_class):
        form = super(EventFormRestrictedQueryset, self).get_form(form_class)
        form.fields['location'].queryset = Location.objects.filter(user=self.request.user)
        form.fields['collaborators'].queryset = Participant.objects.exclude(user=self.request.user)
        return form

class EventDetail(DetailView):
    model = Event
    
    def render_to_response(self, context, **kwargs):
        object = self.get_object()
        if not object.participant.approved():
            # If the current user is the same that has create the event we show it
            if self.request.user == object.participant.user:    
                msg = "Your Event will only be visible once you have been approved as a participant."
                messages.add_message(self.request, messages.INFO, msg)
                context = self.get_context_data(**kwargs)
            else: # for all the other we redirect to the homepage.
                return HttpResponseRedirect(reverse_lazy('home'))
        return super(EventDetail, self).render_to_response(context, **kwargs)
    
    

class EventList(CategoryFilterMixin, ListView):
    
    model = Event
    queryset = Event.objects.filter(participant__approved_on__lt=now())\
        .annotate(first_day=Min('days')).order_by('-featured','-isEvent','-priority')# .order_by('first_day', 'start_time')

    def get_queryset(self):
        queryset = super(EventList, self).get_queryset()

        if self.selected_category_id:
            owner_in_category_query = Q(participant__categories=self.selected_category_id)
            approved_collaborators_query = ~Q(collaborators__approved_on=None)
            collaborators_in_category_query = Q(collaborators__categories=self.selected_category_id)
            queryset = queryset.filter(owner_in_category_query | approved_collaborators_query & collaborators_in_category_query).distinct()

        if self.request.GET.has_key("q"):
            queryset = queryset.filter(name__icontains=self.request.GET["q"])
        return queryset
    
    def get_template_names(self):
        template = super(EventList, self).get_template_names()
        if self.request.is_ajax():
            template = "events/_event_map_list.html"
        return template
    
    def get(self, request, *args, **kwargs):
        if request.is_ajax(): #map has been zoomed or dragged.
            poly, map_bounds = get_search_polygon(request)
            self.object_list = self.get_queryset().filter(location__marker__within=poly)
            context = self.get_context_data(object_list=self.object_list)
            context['map_bounds'] = map_bounds
            return self.render_to_response(context, **kwargs)
        
        else: # we load the page for the first time.
            self.object_list = self.get_queryset()
            context = self.get_context_data(object_list=self.object_list)
            locations = Location.objects.filter(event__in=self.object_list)
            map_bounds = calculate_bounds(locations)
            context['map_bounds'] = map_bounds
            return self.render_to_response(context, **kwargs)

class EventListUser(EventModelOwnerRestrictedMixin, ListView):

    model = Event
    template_name = "events/event_list_user.html"
    
    
                

class EventCreate(EventParticipantApprovedMixin, EventFormRestrictedQueryset, CreateView):
    
    model = Event
    form_class = EventForm

    def form_valid(self, form):
        
        form.instance.participant = self.request.user.participant
        form.save()
        return super(EventCreate, self).form_valid(form)
        

class EventUpdate(EventParticipantApprovedMixin, EventModelOwnerRestrictedMixin, 
                  EventFormRestrictedQueryset, UpdateView):
        
    model = Event
    form_class = EventForm
    template_name = "events/event_form_update.html"
    
    
class EventDelete(EventParticipantApprovedMixin, EventModelOwnerRestrictedMixin, DeleteView):
    
    model = Event
    

eluminate_web/templates/participant/_participant_detail_event_snippet.html
{% load url from future %}
{% load tidy from date_tidy %}

<img src="{{ STATIC_URL }}img/elum_top.png" />
<a href="{{ event.get_absolute_url }}" title="Go to event"><h2>{{ event.name }}</h2></a>
<p>{{ event.description|striptags|urlize|linebreaks|truncatewords_html:15 }}</p>
<div class="row-fluid">
    <div class="span4 participant-event-label">
        Location:
    </div>
    <div class="span8">
        {{ event.location.name }}
    </div>
</div>
<div class="row-fluid">
    <div class="span4 participant-event-label">
        Time:
    </div>
    <div class="span8">
        {{ event.start_time }} until {{ event.end_time }}
    </div>
</div>
<div class="row-fluid">
    <div class="span4 participant-event-label">
        Days:
    </div>
    <div class="span8">
        {{ event.days|tidy }}
    </div>
</div>
<a href="{{ event.get_absolute_url }}" class="btn">Find out more&hellip;</a>

eluminate_web/templates/participant/category_filter.html
{% if category_list|length > 1 %}
<div class="row-fluid">
  <div id="category_filter">
    <div class="span1 offset1">
      Show:&nbsp;&nbsp;
    </div>
    <div class="span10">
      <form method="GET" action="{% url action_url_name %}">
	<span class="nowrap"><input type="radio" name="category" value="0" onclick="this.form.submit();" {% ifequal selected_category_id 0 %}checked{% endifequal %} > All&nbsp;&nbsp;</span>
	{% for category in category_list %}
	<span class="nowrap"><input type="radio" name="category" value="{{ category.id }}" onclick="this.form.submit();" {% ifequal selected_category_id category.id %}checked{% endifequal %}> {{ category.name }}&nbsp;&nbsp;</span>
	{% endfor %}
	<noscript>
	  <input class="btn" type="submit" value="Filter"/>
	</noscript>
      </form>
    </div>
  </div>
</div>
{% endif %}

eluminate_web/templates/participant/participant_base.html
{% extends "site_base.html" %}
{% load i18n %}

{% block head_title %}{% endblock %}

{% block nav_search %}
	{% include '_search_bar.html' with action_url_name='participant_landing' %}
{% endblock %}

{% block body %}
{% block inner_body %}{% endblock %}
{% include "participant/participant_selector.html" %}
{% endblock body %}

eluminate_web/templates/participant/participant_detail.html
{% extends "participant/participant_base.html" %}
{% load i18n %}

{% block head_title %}{{ current_participant.name }}{% endblock %}

{% block inner_body %}
<!-- participant_detail.html -->
<div class="row-fluid participant_detail_row">
    <div class="span8">
        {% if current_participant.website %}
        <a href="{{ current_participant.website }}" target="_blank" title="Go to website">
            <h1>{{ current_participant.name }}</h1>
        </a>
        {% else %}
        <h1>{{ current_participant.name }}</h1>
        {% endif %}
    </div> 
    <div class="span4">
        {% if current_participant.website %}
        <a href="{{ current_participant.website }}" target="_blank" title="Go to website">
            <img id="participant_detail_logo" src="{{ current_participant.logo.url }}"/>
        </a>
        {% else %}
            <img id="participant_detail_logo" src="{{ current_participant.logo.url }}"/>
        {% endif %}
    </div>
</div>
<div class="row-fluid participant_detail_row">
    <div class="span4">
        {% for event in current_participant.own_events.all %}
        <div class="row-fluid">
            <div class="span12 lightBackground participant-event">
                {% include 'participant/_participant_detail_event_snippet.html' %}
            </div>
        </div>
        {% endfor %}
        {% for event in current_participant.approved_collaboration_events %}
        <div class="row-fluid">
            <div class="span12 lightBackground participant-event">
                {% include 'participant/_participant_detail_event_snippet.html' %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="span8">
        <div class="row-fluid">
            {% if current_participant.photo %}
            <div class="span6">
            {% else %}
            <div class="span12">
            {% endif %}
                <p>{{ current_participant.description|striptags|urlize|linebreaks }}<p>
            </div>
            {% if current_participant.photo %}
            <div class="span6">
                {% if current_participant.photo %}
                <img src="{{ current_participant.photo.url }}"/>
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
<div>
    {% if current_participant == request.user.participant %}
    	<a href="{% url 'participant_update' slug=current_participant.slug %}">Update Details</a>
    {% endif %}
</div>

{% endblock inner_body %}

eluminate_web/templates/participant/participant_form.html
{% extends "site_base.html" %}

{% load crispy_forms_tags %}

{% block head_title %}Create Participant{% endblock %}

{% block body %}
{{form.media}}
<h1>Insert your details</h1>

<div class="span8">
    {% crispy form %}
</div>

{% endblock%}

{% block extra_body %}
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.slugify.js"></script>
<script type="text/javascript">$('#id_slug').slugify('#id_name');</script>
{% endblock %}

eluminate_web/templates/participant/participant_landing.html
{% extends "participant/participant_base.html" %}
{% load i18n %}

{% block head_title %}{% trans "Collaborators" %}{% endblock %}

{% block inner_body %}

<div class="row-fluid">
    <div class="span6 offset2">
      <h1>The Collaborators</h1>
        <h2>Browse the people and organisations who have come together to make the  e-Luminate festival happen</h2>
    </div>
</div>

<div class="row-fluid">
    <div class="span8 offset2">
        <p>Click on their thumbnail to see individual details. You can use the “filter” to select particular categories of collaborators</p>
    </div>
</div>

{% endblock inner_body %}

eluminate_web/templates/participant/participant_selector.html
<div class="row-fluid">
    <div class="span12">
        <div id="participant_action_bar" class="lightBackground">
            {% include 'participant/category_filter.html' with action_url_name='participant_filter' %}
            <div class="row-fluid">
                <div class="span12">
                    <div id="participant_selector">
                        {% for participant in participant_list %}
                        <a title="{{ participant.name }}" href="{{ participant.get_absolute_url }}{% if selected_category_id %}?category={{ selected_category_id }}{% endif %}">
                            <div class="participant_logo_box{% if current_participant.id == participant.id %} current_participant{% endif %}">
                                <img class="participant_logo_img" src="{{ participant.logo.url }}" alt="{{ participant.name }}" />
                            </div>
                        </a>
                        {% empty %}
                        <p>Sorry, no participants matched your query. Try altering the filter above.</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>